# Generated by Django 3.1.4 on 2020-12-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Blog',
        ),
    ]
