# Generated by Django 3.1.4 on 2020-12-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201218_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='blog',
        ),
    ]
